---
- hosts: nsxlabhosts
  vars:
   key_file: /etc/nginx/ssl/nginx.key
   cert_file: /etc/nginx/ssl/nginx.crt
   conf_file: /etc/nginx/sites-available/default

  tasks:
   - name: Install nginx
     apt: name=nginx update_cache=yes cache_valid_time=3600
     become: true
   - name: create directories for ssl certificates
     file: path=/etc/nginx/ssl state=directory
     become: true
   - name: copy TLS key
     copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
     notify: restart nginx
     become: true
   - name: copy TLS certificate
     copy: src=files/nginx.crt dest={{ cert_file }}
     notify: restart nginx
     become: true
   - name: copy nginx config file
     template: src=templates/nginx.conf.j2 dest={{ conf_file }}
     notify: restart nginx
     become: true
   - name: enable configuration
     file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
     notify: restart nginx
   - name: copy index.html
     template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
     become: true


#  - name: fix hostname in hosts file
#    template: src=templates/hosts.j2 dest=/etc/hosts
#    become: true


  handlers:
   - name: restart nginx
     service: name=nginx state=restarted
     become: true
